services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      AUTO_SERVER_URL: 1
      IPADDRESS: 192.168.178.108
    ports:
      - "8080:8080"
    volumes:
      - "./stremio-data:/root/.stremio-server"
